### ISSUE TITLE
Is devs overrated

### ISSUE THREAD

**Issue by KieuTuanPhuong** [KieuTuanPhuong/QR_Checkin_Goose#2]

**Comment by MUNALDO** [comment]
The perception of developers as overrated can stem from various factors, including their high demand, the complexity of their work, cultural influences, and the critical role they play in many industries. However, their contributions to innovation, automation, and problem-solving are significant and often justify their prominence and compensation.

Ultimately, whether developers are overrated is a matter of perspective, and recognizing the value of all roles in a collaborative effort can provide a more balanced view.

**Comment by KieuTuanPhuong** [comment]
Indeed
