### ISSUE TITLE
How can I create Issue?

### ISSUE THREAD

**Issue by KieuTuanPhuong** [KieuTuanPhuong/QR_Checkin_Goose#3]

**Comment by MUNALDO** [comment]
## Issue Title: Bug in user login functionality

### Description
There is a bug in the user login functionality where users are unable to log in with valid credentials.

### Steps to Reproduce
1. Go to the login page.
2. Enter valid username and password.
3. Click the "Login" button.

### Expected Results
- The user should be redirected to the dashboard upon successful login.

### Actual Results
- An error message is displayed saying "Invalid credentials," even though the credentials are correct.

### Additional Information
- Browser: Chrome Version 91.0.4472.124 (Official Build) (64-bit)
- OS: Windows 10
- Error Message: "Invalid credentials"

### Screenshots
![login-error](https://user-images.githubusercontent.com/example/login-error.png)

### Labels
- bug

### Assignees
- @username

### Projects
- Login System Overhaul

### Milestones
- Milestone 1.0
